#!/usr/bin/env bash
# Consolidates the per-target JSON + stats logs produced by
# run-traffic-mix-benchmark.sh into a single markdown table with one row
# per (host, scenario), so a variety of hosts and instance types can be
# compared side by side under the mixed workload. Requires jq.
#
# This is the traffic-mix analog of aws/fleet/'s summarize-fleet.sh. The
# per-file helpers below mirror it (including the STRNUM/regex awk gotcha
# in avg_cpu); the table columns are the mixed-workload metrics instead of
# the handshake-only ones.
set -euo pipefail

DIR="${1:-results}"
# targets.env lives one level up from results/ (deploy_root/targets.env);
# it maps host name -> instance type + architecture for the table.
TARGETS_FILE="${TARGETS_FILE:-$DIR/../targets.env}"

if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq is required to summarize results (raw JSON is still in $DIR/*.json)" >&2
  exit 1
fi

field() { # field <json-file> <jq-expr> -> value or "n/a"
  local f="$1" expr="$2"
  if [ -f "$f" ]; then
    jq -r "$expr // \"n/a\"" "$f"
  else
    echo "n/a"
  fi
}

num() { # num <json-file> <jq-expr> <printf-fmt> -> formatted number or "n/a"
  local f="$1" expr="$2" fmt="$3"
  [ -f "$f" ] || { echo "n/a"; return; }
  jq -r "$expr // empty" "$f" | awk -v fmt="$fmt" '{printf fmt, $1; found=1} END {if (!found) print "n/a"}'
}

avg_cpu() { # avg_cpu <stats-log> -> "12.3%" or "n/a"
  local f="$1"
  [ -f "$f" ] || { echo "n/a"; return; }
  # Numeric check is a regex match, not "$1+0==$1": gsub() clears awk's
  # STRNUM flag on the field, and $1+0==$1 then falls back to a string
  # comparison that spuriously fails for values like "3.0".
  awk -F',' '{gsub("%","",$1); if ($1 ~ /^[0-9]+(\.[0-9]+)?$/) {sum+=$1; n++}} END {if (n>0) printf "%.1f%%", sum/n; else print "n/a"}' "$f"
}

last_mem() { # last_mem <stats-log> -> "12.3MB" or "n/a"
  local f="$1"
  [ -f "$f" ] || { echo "n/a"; return; }
  [ -s "$f" ] || { echo "n/a"; return; }
  tail -n1 "$f" | awk -F',' '{print $2}' | awk -F' / ' '{print $1}'
}

# params_line prints a one-line summary of the workload knobs, read from
# whichever result JSON exists. trafficmix records them identically for
# every host+scenario in a run.
params_line() {
  local f
  f="$(ls "$DIR"/*-pqc.json "$DIR"/*-classic.json 2>/dev/null | head -n1)"
  [ -n "$f" ] || { echo "_Run parameters unavailable._"; return; }
  jq -r '.params |
    "_Run parameters: \(.rps) req/s target, \(.handshake_rate) handshakes/s target, " +
    "\(.resume_pct)% resume requested, \(.min_bytes)-\(.max_bytes) byte responses, " +
    "\(.connections) keep-alive conns, \(.duration_s)s (per host+scenario)._"' "$f"
}

# host_meta <name> -> "instance_type arch" (or "n/a n/a"), read from targets.env
host_meta() {
  local name="$1"
  if [ -f "$TARGETS_FILE" ]; then
    awk -v n="$name" '$1==n {print $3, $4; found=1} END {if (!found) print "n/a n/a"}' "$TARGETS_FILE"
  else
    echo "n/a n/a"
  fi
}

emit_row() {
  local name=$1 variant=$2 label
  label="$name-$variant"
  local j="$DIR/$label.json" s="$DIR/$label-stats.log"
  [ -f "$j" ] || return 0
  local meta itype arch
  meta="$(host_meta "$name")"
  itype="${meta% *}"; arch="${meta#* }"
  local scen; [ "$variant" = pqc ] && scen="PQC" || scen="Classic"
  # errors and dropped are summed across both subsystems (saturation shows
  # up as a nonzero dropped count).
  printf '| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n' \
    "$name" "$itype" "$arch" "$scen" \
    "$(field "$j" .tls_group)" \
    "$(num "$j" .request.achieved_rps '%.0f')" \
    "$(num "$j" .request.latency.p50_ms '%.2f')" \
    "$(num "$j" .request.latency.p95_ms '%.2f')" \
    "$(num "$j" .handshake.achieved_rate '%.0f')" \
    "$(num "$j" '(.handshake.resume_rate_actual * 100)' '%.0f%%')" \
    "$(num "$j" .handshake.full_latency.p95_ms '%.2f')" \
    "$(num "$j" .handshake.resumed_latency.p95_ms '%.2f')" \
    "$(num "$j" '(.request.errors + .handshake.errors)' '%d')" \
    "$(num "$j" '(.request.dropped + .handshake.dropped)' '%d')" \
    "$(avg_cpu "$s")/$(last_mem "$s")"
}

# Ordered list of host names: prefer targets.env order; else derive from
# the result filenames.
hosts() {
  if [ -f "$TARGETS_FILE" ]; then
    awk 'NF && $1 !~ /^#/ {print $1}' "$TARGETS_FILE"
  else
    for f in "$DIR"/*-pqc.json; do
      [ -e "$f" ] || continue
      local b; b="$(basename "$f")"; echo "${b%-pqc.json}"
    done
  fi
}

cat <<'EOF'
# NGINX PQC vs ECDHE Traffic-Mix Benchmark: fleet results

A realistic mixed workload (HTTP requests over a warm keep-alive pool +
new-connection TLS handshakes, a share of which resume a session, all
fetching random-sized responses) is generated by the client over the
intra-VPC network; Avg CPU / Mem are the target's own nginx master+worker
usage during the run. Compare PQC vs Classic within a host, and hosts
against each other. Req/s and Handshakes/s are the *achieved* rates; a
nonzero Dropped count means the target (or client) could not keep up with
the requested rate. Handshake latencies are split by whether the
connection actually resumed (full vs resumed).
EOF
echo
params_line
cat <<'EOF'

| Host | Instance type | Arch | Scenario | TLS Group | Req/s | Req p50 (ms) | Req p95 (ms) | HS/s | Resume % | HS full p95 (ms) | HS resume p95 (ms) | Errors | Dropped | CPU / Mem |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
EOF

while read -r name; do
  [ -z "${name:-}" ] && continue
  emit_row "$name" pqc
  emit_row "$name" classic
done < <(hosts)
